export const GET_BASE_INFO = 'GET_BASE_INFO'
export const SET_BASE_INFO = 'SET_BASE_INFO'

export const GET_TOP_GROUPS = 'GET_TOP_GROUPS'
export const SET_TOP_GROUPS = 'SET_TOP_GROUPS'

export const SET_SUB_GROUPS = 'SET_SUB_GROUPS'
export const GET_SUB_GROUPS = 'GET_SUB_GROUPS'

export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET'
export const CHANGE_COUNT_PRODUCT_BASKET = 'CHANGE_COUNT_PRODUCT_BASKET'
export const DELETE_PRODUCT_BASKET = 'DELETE_PRODUCT_BASKET'
export const CLEAN_PRODUCT_BASKET = 'CLEAN_PRODUCT_BASKET'

export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'

export const GET_SOCIALS = 'GET_SOCIALS'
export const SET_SOCIALS = 'SET_SOCIALS'
export const GET_ADDITIONAL_INFO = 'GET_ADDITIONAL_INFO'
export const SET_ADDITIONAL_INFO = 'SET_ADDITIONAL_INFO'
